"""Q1.H2.E3 — generate dialogue-form probe data for the 12 battery emotions.

The paper's appendix reports that probes built from dialogues rather than
third-person stories behave similarly; our E1 result makes story-to-dialogue
transfer a live suspect, so we rebuild probe data as dialogues and re-score.
Generation happens on the extraction model itself (documented deviation: the
original story corpus was generated by a 4B model). One JSONL row per dialogue
is appended as it is produced, so the run is resumable; the grouped
{emotion, stories} file the extraction pipeline reads is assembled at the end.

    uv run python scripts/generate_dialogue_stories.py  # on the pod, tmux

Backends: --backend vllm (default; continuous batching — measured ~9 min for
2,424 stories where the HF loop needed hours) or --backend hf (dependency-free
fallback; launchers auto-fall-back on nonzero vllm exit).

vllm setup is NOT pip-install-and-go on the Blackwell pod: run
scripts/pod/setup_vllm_env.sh once and export VLLM_ATTENTION_BACKEND=TRITON_ATTN
and VLLM_USE_FLASHINFER_SAMPLER=0 in the launcher. Symptom table for the three
failure modes: notes/vllm-parallel-inference-template.md (Blackwell survival
guide). vllm stays out of pyproject: no macOS wheels, generation-only.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from emotion_vectors.probe_prompts import SCENARIOS

try:
    from emotion_vectors.extraction import load_model_bf16, setup_logger
except ModuleNotFoundError as exc:  # torch lives in the gpu extra; this is a GPU entry point
    raise SystemExit(f"missing {exc.name}: this entry point needs `uv sync --extra gpu`") from exc

INSTRUCTIONS = {
    "dialogue": (
        "Write a short scene of dialogue between two people, around 150 words, in which one of "
        "them is experiencing {emotion}. Do not name the emotion anywhere in the text. Use the "
        "format:\nA: ...\nB: ..."
    ),
    "story": (
        "Write a short third-person story, around 150 words, about a person experiencing "
        "{emotion}. Do not name the emotion anywhere in the text."
    ),
    "neutral": (
        "Write a short, emotionally neutral third-person transcript of an everyday activity "
        "(for example: assembling furniture, following a recipe, describing a commute, "
        "documenting an inventory), around 150 words. Keep it strictly factual and free of "
        "emotional content."
    ),
}


def gen_prompt(tokenizer: object, emotion: str, style: str) -> str:
    instruction = (
        INSTRUCTIONS[style].format(emotion=emotion) if style != "neutral" else INSTRUCTIONS[style]
    )
    if tokenizer.chat_template:
        return tokenizer.apply_chat_template(
            [{"role": "user", "content": instruction}], tokenize=False, add_generation_prompt=True
        )
    return f"Task: {instruction}\n\n" + ("Dialogue:\nA:" if style == "dialogue" else "Story:")


def existing_counts(path: Path) -> dict[str, int]:
    counts: dict[str, int] = {}
    if path.exists():
        with open(path) as f:
            for line in f:
                if line.strip():
                    counts[json.loads(line)["emotion"]] = (
                        counts.get(json.loads(line)["emotion"], 0) + 1
                    )
    return counts


def generate_batch(lm: object, prompt: str, n: int, seed: int, max_new: int) -> list[str]:
    import torch  # noqa: PLC0415

    torch.manual_seed(seed)
    inputs = lm.tokenizer([prompt] * n, return_tensors="pt").to(lm.model.device)
    with torch.inference_mode():
        out = lm.model.generate(
            **inputs, max_new_tokens=max_new, do_sample=True, temperature=0.9, top_p=0.95
        )
    completions = lm.tokenizer.batch_decode(
        out[:, inputs["input_ids"].shape[1] :], skip_special_tokens=True
    )
    return [c.strip() for c in completions if len(c.strip()) > 100]


def pending_prompts(
    counts: dict[str, int], emotions: list[str], args: object, tokenizer: object
) -> list[tuple[str, str]]:
    todo: list[tuple[str, str]] = []
    for emotion in emotions:
        need = args.per_emotion - counts.get(emotion, 0)
        todo += [(emotion, gen_prompt(tokenizer, emotion, args.style))] * max(0, need)
    return todo


def run_vllm(args: object, emotions: list[str], raw_path: Path, logger: object) -> None:
    """Generate every pending completion in one continuously-batched pass,
    with one top-up round for completions the length filter rejects."""
    from transformers import AutoTokenizer  # noqa: PLC0415
    from vllm import LLM, SamplingParams  # noqa: PLC0415 — pod-only dependency

    tokenizer = AutoTokenizer.from_pretrained(args.model, trust_remote_code=True)
    # enforce_eager: this card (SM 12.x Blackwell) trips vLLM's compile path on
    # CUDA < 12.9 wheels; eager mode skips it. max_model_len bounds the KV cache
    # (defaults to the model's 262k context, far beyond these ~500-token prompts).
    llm = LLM(
        model=args.model, dtype="bfloat16", seed=args.seed, enforce_eager=True, max_model_len=2048
    )
    for round_idx in range(2):
        counts = existing_counts(raw_path)
        todo = pending_prompts(counts, emotions, args, tokenizer)
        if not todo:
            break
        logger.info(f"vllm round {round_idx}: {len(todo)} completions pending")
        params = [
            SamplingParams(
                temperature=0.9,
                top_p=0.95,
                max_tokens=args.max_new_tokens,
                seed=args.seed + round_idx * 100_000 + i,
            )
            for i in range(len(todo))
        ]
        outputs = llm.generate([prompt for _, prompt in todo], params)
        kept = 0
        with open(raw_path, "a") as f:
            for (emotion, _), out in zip(todo, outputs):
                text = out.outputs[0].text.strip()
                if len(text) > 100:
                    f.write(json.dumps({"emotion": emotion, "text": text}) + "\n")
                    kept += 1
        logger.info(f"vllm round {round_idx}: kept {kept}/{len(todo)}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", default="google/gemma-4-31b")
    parser.add_argument("--backend", choices=["vllm", "hf"], default="vllm")
    parser.add_argument("--style", choices=list(INSTRUCTIONS), default="dialogue")
    parser.add_argument("--per-emotion", type=int, default=16)
    parser.add_argument("--batch-size", type=int, default=8)
    parser.add_argument("--max-new-tokens", type=int, default=300)
    parser.add_argument("--seed", type=int, default=20260721)
    parser.add_argument("--out-dir", type=Path, default=Path("results/dialogue_stories"))
    args = parser.parse_args()

    logger = setup_logger(args.out_dir / "generate.log")
    raw_path = args.out_dir / "dialogues_raw.jsonl"
    emotions = ["neutral"] if args.style == "neutral" else [target for _, target, _ in SCENARIOS]
    counts = existing_counts(raw_path)
    logger.info(f"{len(emotions)} emotions x {args.per_emotion}; resuming from {counts or '{}'}")
    if args.backend == "vllm":
        run_vllm(args, emotions, raw_path, logger)
        counts = existing_counts(raw_path)
        emotions_hf: list[str] = []  # vllm path handles everything
    else:
        emotions_hf = emotions
    if emotions_hf:
        lm, _ = load_model_bf16(args.model, logger.info)

    for emotion in emotions_hf:
        batch_idx = 0
        while counts.get(emotion, 0) < args.per_emotion:
            texts = generate_batch(
                lm,
                gen_prompt(lm.tokenizer, emotion, args.style),
                min(args.batch_size, args.per_emotion - counts.get(emotion, 0)),
                args.seed + hash(emotion) % 10_000 + batch_idx,
                args.max_new_tokens,
            )
            batch_idx += 1
            with open(raw_path, "a") as f:
                for text in texts:
                    f.write(json.dumps({"emotion": emotion, "text": text}) + "\n")
            counts[emotion] = counts.get(emotion, 0) + len(texts)
            logger.info(f"[{emotion}] {counts[emotion]}/{args.per_emotion}")
        logger.info(f"[{emotion}] sample: {open(raw_path).readlines()[-1][:160]}")

    grouped: dict[str, list[str]] = {}
    with open(raw_path) as f:
        for line in f:
            row = json.loads(line)
            grouped.setdefault(row["emotion"], []).append(row["text"])
    (args.out_dir / "dialogues_grouped.jsonl").write_text(
        "".join(
            json.dumps({"emotion": e, "stories": s[: args.per_emotion]}) + "\n"
            for e, s in grouped.items()
        )
    )
    logger.info(f"grouped {len(grouped)} emotions -> {args.out_dir / 'dialogues_grouped.jsonl'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
