"""Q1.H2.E3 — generate dialogue-form probe data for the 12 battery emotions.

The paper's appendix reports that probes built from dialogues rather than
third-person stories behave similarly; our E1 result makes story-to-dialogue
transfer a live suspect, so we rebuild probe data as dialogues and re-score.
Generation happens on the extraction model itself (documented deviation: the
original story corpus was generated by a 4B model). One JSONL row per dialogue
is appended as it is produced, so the run is resumable; the grouped
{emotion, stories} file the extraction pipeline reads is assembled at the end.

    uv run python scripts/generate_dialogue_stories.py  # on the pod, tmux
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from emotion_vectors.probe_prompts import SCENARIOS

try:
    from emotion_vectors.extraction import load_model_bf16, setup_logger
except ModuleNotFoundError as exc:  # torch lives in the gpu extra; this is a GPU entry point
    raise SystemExit(f"missing {exc.name}: this entry point needs `uv sync --extra gpu`") from exc

INSTRUCTIONS = {
    "dialogue": (
        "Write a short scene of dialogue between two people, around 150 words, in which one of "
        "them is experiencing {emotion}. Do not name the emotion anywhere in the text. Use the "
        "format:\nA: ...\nB: ..."
    ),
    "story": (
        "Write a short third-person story, around 150 words, about a person experiencing "
        "{emotion}. Do not name the emotion anywhere in the text."
    ),
    "neutral": (
        "Write a short, emotionally neutral third-person transcript of an everyday activity "
        "(for example: assembling furniture, following a recipe, describing a commute, "
        "documenting an inventory), around 150 words. Keep it strictly factual and free of "
        "emotional content."
    ),
}


def gen_prompt(tokenizer: object, emotion: str, style: str) -> str:
    instruction = (
        INSTRUCTIONS[style].format(emotion=emotion) if style != "neutral" else INSTRUCTIONS[style]
    )
    if tokenizer.chat_template:
        return tokenizer.apply_chat_template(
            [{"role": "user", "content": instruction}], tokenize=False, add_generation_prompt=True
        )
    return f"Task: {instruction}\n\n" + ("Dialogue:\nA:" if style == "dialogue" else "Story:")


def existing_counts(path: Path) -> dict[str, int]:
    counts: dict[str, int] = {}
    if path.exists():
        with open(path) as f:
            for line in f:
                if line.strip():
                    counts[json.loads(line)["emotion"]] = (
                        counts.get(json.loads(line)["emotion"], 0) + 1
                    )
    return counts


def generate_batch(lm: object, prompt: str, n: int, seed: int, max_new: int) -> list[str]:
    import torch  # noqa: PLC0415

    torch.manual_seed(seed)
    inputs = lm.tokenizer([prompt] * n, return_tensors="pt").to(lm.model.device)
    with torch.inference_mode():
        out = lm.model.generate(
            **inputs, max_new_tokens=max_new, do_sample=True, temperature=0.9, top_p=0.95
        )
    completions = lm.tokenizer.batch_decode(
        out[:, inputs["input_ids"].shape[1] :], skip_special_tokens=True
    )
    return [c.strip() for c in completions if len(c.strip()) > 100]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", default="google/gemma-4-31b")
    parser.add_argument("--style", choices=list(INSTRUCTIONS), default="dialogue")
    parser.add_argument("--per-emotion", type=int, default=16)
    parser.add_argument("--batch-size", type=int, default=8)
    parser.add_argument("--max-new-tokens", type=int, default=300)
    parser.add_argument("--seed", type=int, default=20260721)
    parser.add_argument("--out-dir", type=Path, default=Path("results/dialogue_stories"))
    args = parser.parse_args()

    logger = setup_logger(args.out_dir / "generate.log")
    raw_path = args.out_dir / "dialogues_raw.jsonl"
    emotions = ["neutral"] if args.style == "neutral" else [target for _, target, _ in SCENARIOS]
    counts = existing_counts(raw_path)
    logger.info(f"{len(emotions)} emotions x {args.per_emotion}; resuming from {counts or '{}'}")
    lm, _ = load_model_bf16(args.model, logger.info)

    for emotion in emotions:
        batch_idx = 0
        while counts.get(emotion, 0) < args.per_emotion:
            texts = generate_batch(
                lm,
                gen_prompt(lm.tokenizer, emotion, args.style),
                min(args.batch_size, args.per_emotion - counts.get(emotion, 0)),
                args.seed + hash(emotion) % 10_000 + batch_idx,
                args.max_new_tokens,
            )
            batch_idx += 1
            with open(raw_path, "a") as f:
                for text in texts:
                    f.write(json.dumps({"emotion": emotion, "text": text}) + "\n")
            counts[emotion] = counts.get(emotion, 0) + len(texts)
            logger.info(f"[{emotion}] {counts[emotion]}/{args.per_emotion}")
        logger.info(f"[{emotion}] sample: {open(raw_path).readlines()[-1][:160]}")

    grouped: dict[str, list[str]] = {}
    with open(raw_path) as f:
        for line in f:
            row = json.loads(line)
            grouped.setdefault(row["emotion"], []).append(row["text"])
    (args.out_dir / "dialogues_grouped.jsonl").write_text(
        "".join(
            json.dumps({"emotion": e, "stories": s[: args.per_emotion]}) + "\n"
            for e, s in grouped.items()
        )
    )
    logger.info(f"grouped {len(grouped)} emotions -> {args.out_dir / 'dialogues_grouped.jsonl'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
