"""Publish the generated text corpora and derived vectors to Hugging Face.

The reference project published its generated story corpus (our input data
came from exactly such a publication), so ours are published the same way:
one private dataset repo per corpus, raw + grouped JSONL + generation log,
with a card recording generator model, style, constraint, and leakage QC.
Vector directories that already carry a run_config.json are re-published via
the standard hf_publish flow.

    uv run python scripts/publish_generated_corpora.py  # pod (needs HF_TOKEN)
"""

from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path

from huggingface_hub import HfApi

from emotion_vectors.extraction import setup_logger
from emotion_vectors.hf_publish import publish

CORPORA: list[tuple[str, str, str]] = [
    # (results subdir, repo suffix, description)
    (
        "dialogue_stories",
        "emotion-dialogues-gemma-4-31b",
        "two-person dialogues, base model, 12 battery emotions x 16 (leakage 44% — kept as the "
        "documented base-arm artefact)",
    ),
    (
        "dialogue_stories_it",
        "emotion-dialogues-gemma-4-31b-it",
        "two-person dialogues, instruct model, 12 battery emotions x 16 (leakage 0%)",
    ),
    (
        "self_stories_it",
        "emotion-stories-gemma-4-31b-it",
        "third-person stories generated by the probed model itself, 12 battery emotions "
        "(E6 scale corpus; leakage ~1% at pilot QC)",
    ),
    (
        "neutral_transcripts_it",
        "neutral-transcripts-gemma-4-31b-it",
        "emotionally neutral everyday transcripts for the neutral-PC confound projection (E7)",
    ),
]

VECTOR_DIRS: list[tuple[str, str]] = [
    ("dialogue_vectors", "emotion-dialogue-vectors-gemma-4-31b"),
    ("dialogue_vectors_it", "emotion-dialogue-vectors-gemma-4-31b-it"),
    ("self_story_vectors_it", "emotion-selfstory-vectors-gemma-4-31b-it"),
    ("neutral_vectors_it", "neutral-vectors-gemma-4-31b-it"),
]


def corpus_card(subdir: str, description: str) -> str:
    return (
        f"# {subdir}\n\n{description}\n\n"
        "Generated by [gemma4-emotion-vectors](https://github.com/Antonio-Tresol/gemma4-emotion-vectors)"
        " `scripts/generate_dialogue_stories.py` (instruction includes 'do not name the emotion';"
        " leakage QC in the research log). Files: `dialogues_raw.jsonl` (one row per text),"
        " `dialogues_grouped.jsonl` ({emotion, stories} rows, the extraction pipeline's input),"
        " `generate.log`.\n"
    )


def publish_corpus(
    api: HfApi, results: Path, spec: tuple[str, str, str], logger: logging.Logger
) -> None:
    subdir, suffix, description = spec
    src = results / subdir
    if not (src / "dialogues_grouped.jsonl").exists():
        logger.warning(f"skip {subdir}: no grouped file")
        return
    repo = f"{api.whoami()['name']}/{suffix}"
    api.create_repo(repo, repo_type="dataset", private=True, exist_ok=True)
    (src / "README.md").write_text(corpus_card(subdir, description))
    api.upload_folder(folder_path=str(src), repo_id=repo, repo_type="dataset")
    logger.info(f"published (private) -> https://huggingface.co/datasets/{repo}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--results", type=Path, default=Path("results"))
    args = parser.parse_args()
    logger = setup_logger(args.results / "publish_corpora.log")
    api = HfApi()
    for spec in CORPORA:
        publish_corpus(api, args.results, spec, logger)
    for subdir, suffix in VECTOR_DIRS:
        if (args.results / subdir / "run_config.json").exists():
            publish(args.results / subdir, suffix, smoke=False, logger=logger)
        else:
            logger.warning(f"skip vectors {subdir}: no run_config.json")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
