"""Publish the Q3 combined-story corpus and trajectory substrate to HF.

Two private datasets (public together at sprint end, after the
validate-claims gate, like every other repo of this project):

- emotion-combined-stories-gemma-4-31b-it — the 5,888-story corpus
  (three emotions per story, SIMULTANEOUS/SEQUENTIAL modes) plus the triples
  spec, generation config, and log.
- emotion-combined-trajectories-gemma-4-31b-it — the per-token substrate:
  one shard per story with raw dots onto 207 unit probes at 6 layers,
  raw/centered norms, residual speed, token ids, and phase starts. Centered
  cosines and every figure are numpy transformations of these shards.

    .venv/bin/python scripts/combined_story_gen/publish_combined.py  # pod

Uploads small files as bytes (the LFS-pointer workaround) and shards via
upload_folder.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from huggingface_hub import HfApi

try:  # laptop convenience; the pod launcher sources .env instead
    from dotenv import load_dotenv
except ModuleNotFoundError:

    def load_dotenv() -> None:
        return None


STORIES_CARD = """---
license: gemma
---
# emotion-combined-stories-gemma-4-31b-it

5,888 short stories, each conveying THREE emotions, generated by
google/gemma-4-31b-it about itself-adjacent fictional characters for the
CBAI sprint's Q3 (temporal dynamics of emotion representations). Companion
to the project's single-emotion corpora; the probed model is the generator
(the self-generated lineage convention, see the project TREE Q1.H2.E10).

## Data lineage

- Generator: google/gemma-4-31b-it via vLLM (seed 20260721, temperature 1.3,
  top-p 0.97, max 450 new tokens; full config in `run_config.json`).
- Prompt spec: 173 emotion triples (`emotions_triples_v1.json`, categories
  incl. conflict pairs and non-affect controls) x 12 combos (6 permutations
  x 2 modes) x 3 samples. Diversity enforced by per-(triple, combo) seeds
  and varied character/setting instructions (top character name appears in
  3.3% of stories).
- Modes: SEQUENTIAL (three phases marked by `<emotion>label</emotion>` tags,
  including at position 0) and SIMULTANEOUS (one tag listing all three).
- QC drops (not in this file): 189 emotion-word leaks, 151 tag mismatches,
  0 too-short. Kept rows have `error: null`, empty `leaked_words`, and
  `tags_match_emotions: true`.

## Files

- `stories_raw.jsonl` — one story per row with triple/mode/permutation
  metadata, QC fields, and the tagged text.
- `stories_grouped.jsonl` — the same stories grouped per triple.
- `emotions_triples_v1.json`, `run_config.json`, `generate.log`.
"""

TRAJ_CARD = """---
license: gemma
---
# emotion-combined-trajectories-gemma-4-31b-it

Per-token trajectory substrate for the CBAI sprint's Q3: how emotion-concept
representations evolve across a story's tokens. One shard per story from the
companion corpus (emotion-combined-stories-gemma-4-31b-it), extracted with a
teacher-forced forward pass through google/gemma-4-31b-it (bf16, RIGHT
padding — post-dates the padding-side instrument fix, project TREE Q1.H3.E4).

## Open-science contract

The shards are the measurement substrate: raw per-token dot products onto
unit probe directions plus the norms that cosines need. Every analysis
quantity is a numpy transformation of these files — no inference required
to replicate. Centered cosine per token t, layer l, probe p:

    d = dots[t, l] - dots[:, l].mean(0)     # dots are linear
    cos = d[p] / norms_centered[t, l]

## Files

- `shards/{story_id}.npz` — `dots` [tokens, 6 layers, 207 probes] fp16;
  `norms`, `norms_centered` [tokens, 6]; `speed` [tokens-1, 6]
  (||a_t - a_{t-1}||); `token_ids`; `phase_token_starts`.
- `manifest.jsonl` — one row per story: triple, mode, phase emotions,
  phase token starts, token count, text hash.
- `probe_labels.json` — the 207 probe names in dots order:
  `corpus:{emotion}` (171, external-corpus lineage), `selfgen:{emotion}`
  (12, self-generated n=256 lineage — the two lineages are distinct objects,
  see TREE Q1.H2.E6/E10), `random:{i}` (24, fixed-seed null directions).
- `run_config.json` — layers [6, 15, 24, 33, 42, 51], model, seed, commit.
- `extract.log` — full run log (5,888 stories, 0 errors, 588 tok/s).

## Storage precision

fp16 shards: relative quantization ~1e-3; end-to-end centered-cosine
reproducibility across compute paths verified to <0.005 absolute.
"""


def upload_small(api: HfApi, repo: str, path: Path, name: str | None = None) -> None:
    api.upload_file(
        path_or_fileobj=path.read_bytes(),
        path_in_repo=name or path.name,
        repo_id=repo,
        repo_type="dataset",
    )


BASE_TRAJ_CARD = """---
license: gemma
---
# emotion-combined-trajectories-gemma-4-31b

BASE-model arm of the per-token trajectory substrate (companion to
emotion-combined-trajectories-gemma-4-31b-it, same corpus and layout). One
shard per story from a teacher-forced forward pass through google/gemma-4-31b
(base, bf16, right padding), residual captured at layers [6, 15, 24, 33, 42, 51].

## Lineage caveats specific to this arm

- The stories were generated by the INSTRUCT model (base cannot chat-write
  stories), so for this arm generator != probed model. Documented, unavoidable.
- Probes: 171 base-corpus-lineage contrasts + 24 fixed-seed random null
  directions (195 total, `probe_labels.json`). There is NO self-generated
  lineage for base, for the same reason.

Schema, centered-cosine recipe, and precision notes: see the -it companion
dataset card. Extraction: 5,888 stories, 0 errors (`extract.log`).
"""


def publish_base_arm(api: HfApi, user: str, traj_dir: Path) -> None:
    repo = f"{user}/emotion-combined-trajectories-gemma-4-31b"
    api.create_repo(repo, repo_type="dataset", private=False, exist_ok=True)
    for name in ("manifest.jsonl", "run_config.json", "probe_labels.json", "extract.log"):
        upload_small(api, repo, traj_dir / name)
    api.upload_file(
        path_or_fileobj=BASE_TRAJ_CARD.encode(),
        path_in_repo="README.md",
        repo_id=repo,
        repo_type="dataset",
    )
    api.upload_folder(
        repo_id=repo,
        repo_type="dataset",
        folder_path=str(traj_dir / "shards"),
        path_in_repo="shards",
        allow_patterns=["*.npz"],
    )
    print(f"base trajectories -> {repo}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--results", type=Path, default=Path("results"))
    parser.add_argument("--stories-dir", type=Path, default=None)
    parser.add_argument(
        "--base-only", action="store_true", help="publish only the base trajectory arm"
    )
    args = parser.parse_args()
    load_dotenv()
    api = HfApi()
    user = api.whoami()["name"]
    if args.base_only:
        publish_base_arm(api, user, args.results / "combined_trajectories_base")
        return 0
    stories_dir = args.stories_dir or (args.results / "combined_stories")
    traj_dir = args.results / "combined_trajectories"

    stories_repo = f"{user}/emotion-combined-stories-gemma-4-31b-it"
    api.create_repo(stories_repo, repo_type="dataset", private=True, exist_ok=True)
    for name in ("stories_raw.jsonl", "stories_grouped.jsonl", "run_config.json", "generate.log"):
        upload_small(api, stories_repo, stories_dir / name)
    upload_small(
        api,
        stories_repo,
        Path("scripts/combined_story_gen/emotions_triples_v1.json"),
    )
    api.upload_file(
        path_or_fileobj=STORIES_CARD.encode(),
        path_in_repo="README.md",
        repo_id=stories_repo,
        repo_type="dataset",
    )
    print(f"stories -> {stories_repo}")

    traj_repo = f"{user}/emotion-combined-trajectories-gemma-4-31b-it"
    api.create_repo(traj_repo, repo_type="dataset", private=True, exist_ok=True)
    for name in ("manifest.jsonl", "run_config.json", "probe_labels.json", "extract.log"):
        upload_small(api, traj_repo, traj_dir / name)
    api.upload_file(
        path_or_fileobj=TRAJ_CARD.encode(),
        path_in_repo="README.md",
        repo_id=traj_repo,
        repo_type="dataset",
    )
    api.upload_folder(
        repo_id=traj_repo,
        repo_type="dataset",
        folder_path=str(traj_dir / "shards"),
        path_in_repo="shards",
        allow_patterns=["*.npz"],
    )
    print(f"trajectories -> {traj_repo}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
